version: "3"
services:
  php_dev:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    depends_on:
      - db
    volumes:
      - .:/var/www/html
    ports:
      - "8888:80"
  db:
    image: mysql:5.7
    ports:
      - 13306:3306
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: docker_php
      MYSQL_ROOT_PASSWORD: password
volumes:
  db:
    driver: local